server:
 port: 0
eureka:
 client:
  service-url:
   defaultZone: http://eureka1:8761/eureka/
spring:
 data:
  mongodb:
   password: '{cipher}AQAQsn0rMLUiYtDqBAC7b6u/azPQSuQsZpyw+TyuBm1ujg8B6zCsjiY3lIGqzoy6JlgAsj+BuSt59XKcBje/rQJloWPJgrdDNbAxvW6mxBKtqoSg6rCXzecjKF1v/fegW6Ibb/EWzieYb8TOVi2P4C3ZY3HYDK21+2MPI3yfX4nxT3UC0v8E4WQ8hw/qBmYLrW/IkZ9dC5o98r09Ykru3IJQOjg9fcNMfgEafRpcBR1EWdlghHmZN4GtO50ma8IiQ6xqxqldkBEW4KFhZcL86i0OEsu3QL7AAQXcXqZFfg6HwWG8hHxWz/H1S04GcRiOOfB3xhzZQ5fz1Q2ed9pf0oxf84Ya+MKpOzr+M9f2Smm88nZ2l49QvW+azRHF/3fJ26o='
